### ISSUE TITLE
[ Server] 각 지역에따른 응답률 필터링

### ISSUE THREAD

**Issue by godyuo** [oxopolitics-internship-for-codestates/Osori#30]
### Issue 타입
- [ x ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 상세 내용
각 지역의 응답률을 나타내기위한 데이터 필터링

**Comment by karuiner** [comment]
작업 완료
