### ISSUE TITLE
[Server] 서울지역 각 구 전체지역 응답률 필터링

### ISSUE THREAD

**Issue by godyuo** [oxopolitics-internship-for-codestates/Osori#32]
### Issue 타입
- [ x ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 상세 내용
서울지역 각 구 전체지역 응답률 필터링

**Comment by karuiner** [comment]
작업 완료
